### ISSUE TITLE
Debug ProtocolAlreadyTerminated tests failure

### ISSUE THREAD

**Issue by Ra1issa** [boltlabs-inc/tss-ecdsa#304]
There seems to be several instances where tests fail with the error `ProtocolAlreadyTerminated. I am listing below all the ones that I have found so far. 

- Keygen: For the example test seeds specified below, the `keygen::participant::tests::keygen_produces_valid_outputs` and `keygen::participant::tests::keygen_always_produces_valid_outputs` tests do not pass. This happens on average 1/2000 runs. 

``` rust
let failing_seed1 =  [206, 176, 109, 77, 209, 109, 105, 131, 244, 104, 70, 0, 115, 113, 39, 202, 108, 188, 31, 130, 248, 200, 236, 102, 49, 50, 130, 28, 221, 110, 125, 114];

let failing_seed2 =   [154, 141, 247, 172, 203, 143, 1, 236, 253, 238, 6, 227, 112, 49, 95, 101, 21, 208, 194, 211, 255, 76, 243, 116, 10, 235, 26, 12, 26, 90, 46, 249];

let failing_seed3 =   [182, 13, 46, 200, 120, 117, 65, 234, 221, 84, 248, 151, 179, 9, 243, 218, 169, 125, 42, 123, 251, 164, 146, 84, 47, 84, 128, 64, 200, 172, 64, 4];

let failing_seed4 =   [206, 188, 103, 17, 119, 86, 84, 39, 58, 234, 4, 184, 250, 44, 183, 162, 247, 130, 251, 68, 204, 68, 146, 169, 136, 97, 96, 21, 210, 5, 176, 28];

let failing_seed5 =  [211, 11, 148, 171, 137, 231, 132, 96, 209, 38, 24, 161, 155, 114, 16, 168, 149, 26, 99, 17, 244, 136, 107, 1, 2, 154, 124, 230, 222, 33, 200, 116];

```

- Protocol:  For the example test seed specified below, the `protocol::tests::full_protocol_execution_works` test does not pass. 

``` rust
let failing_seed1 =  [14, 38, 41, 111, 111, 98, 212, 124, 207, 115, 177, 155, 155, 45, 4, 132, 81, 113, 34, 157, 11, 159, 62, 158, 225, 222, 19, 98, 251, 234, 140, 196];
```

**Comment by gatoWololo** [comment]
I encountered this problem in CI.

```
---- keygen::participant::tests::keygen_always_produces_valid_outputs stdout ----
Test Failed. To recreate the randomness used, use init_testing_with_seed() with the following seed:
seed: [54, 57, 179, 125, 45, 111, 84, 104, 138, 108, 119, 239, 175, 194, 75, 153, 99, 11, 100, 101, 113, 123, 20, 81, 177, 22, 130, 61, 158, 81, 54, 230]
Test Failed. To recreate the randomness used, use init_testing_with_seed() with the following seed:
seed: [123, 70, 103, 200, 218, 22, 39, 168, 188, 107, 66, 97, 201, 0, 132, 210, 28, 57, 227, 238, 101, 90, 126, 118, 41, 77, 162, 154, 95, 64, 156, 173]
Test Failed. To recreate the randomness used, use init_testing_with_seed() with the following seed:
seed: [201, 177, 85, 146, 100, 74, 103, 194, 179, 59, 202, 183, 236, 201, 207, 240, 145, 45, 247, 184, 19, 122, 147, 64, 225, 30, 58, 126, 144, 43, 134, 96]
Test Failed. To recreate the randomness used, use init_testing_with_seed() with the following seed:
seed: [134, 17, 20, 143, 189, 70, 150, 66, 32, 137, 72, 202, 246, 33, 139, 226, 145, 138, 179, 39, 190, 85, 91, 100, 185, 97, 131, 27, 107, 20, 55, 125]
Test Failed. To recreate the randomness used, use init_testing_with_seed() with the following seed:
seed: [32, 60, 4, 112, 118, 3, 14, 252, 102, 154, 111, 143, 178, 155, 221, 127, 125, 71, 206, 139, 105, 93, 36, 49, 10, 141, 92, 233, 43, 3, 44, 103]
Test Failed. To recreate the randomness used, use init_testing_with_seed() with the following seed:
seed: [9, 217, 149, 158, 227, 18, 239, 181, 176, 126, 63, 192, 72, 108, 90, 198, 152, 96, 117, 106, 93, 53, 140, 47, 253, 192, 78, 43, 59, 5, 46, 164]
Test Failed. To recreate the randomness used, use init_testing_with_seed() with the following seed:
seed: [62, 71, 14, 202, 233, 28, 233, 238, 124, 183, 7, 132, 59, 251, 171, 205, 37, 138, 117, 101, 184, 198, 2, 254, 79, 187, 212, 71, 114, 122, 12, 214]
Test Failed. To recreate the randomness used, use init_testing_with_seed() with the following seed:
seed: [157, 113, 133, 16, 21, 126, 134, 118, 164, 96, 88, 15, 141, 85, 78, 111, 2, 8, 106, 97, 139, 113, 9, 230, 50, 109, 53, 10, 171, 245, 52, 91]
Test Failed. To recreate the randomness used, use init_testing_with_seed() with the following seed:
seed: [226, 236, 19, 240, 88, 19, 183, 146, 56, 206, 32, 140, 185, 220, 81, 204, 171, 59, 178, 167, 36, 238, 215, 25, 159, 178, 215, 249, 164, 19, 28, 27]
Test Failed. To recreate the randomness used, use init_testing_with_seed() with the following seed:
seed: [144, 68, 76, 16, 145, 200, 224, 245, 221, 83, 50, 188, 103, 172, 171, 200, 96, 92, 102, 126, 59, 31, 71, 160, 123, 140, 212, 126, 118, 117, 103, 63]
Test Failed. To recreate the randomness used, use init_testing_with_seed() with the following seed:
seed: [181, 77, 3, 175, 6, 253, 1, 228, 252, 169, 164, 53, 72, 56, 92, 44, 243, 125, 146, 73, 242, 27, 243, 15, 45, 130, 122, 86, 136, 181, 244, 116]
Test Failed. To recreate the randomness used, use init_testing_with_seed() with the following seed:
seed: [253, 37, 104, 1, 229, 245, 82, 77, 24, 41, 15, 106, 150, 17, 195, 151, 242, 59, 4, 197, 25, 84, 33, 192, 38, 25, 44, 191, 124, 94, 192, 44]
Test Failed. To recreate the randomness used, use init_testing_with_seed() with the following seed:
seed: [227, 145, 240, 82, 242, 211, 134, 41, 153, 136, 19, 14, 156, 246, 225, 147, 232, 125, 98, 76, 139, 114, 70, 34, 184, 69, 220, 190, 49, 236, 66, 25]
Test Failed. To recreate the randomness used, use init_testing_with_seed() with the following seed:
seed: [1, 43, 233, 204, 207, 6, 20, 10, 193, 177, 251, 46, 105, 248, 32, 161, 88, 62, 108, 142, 41, 192, 54, 62, 47, 209, 195, 12, 214, 18, 72, 87]
thread 'keygen::participant::tests::keygen_always_produces_valid_outputs' panicked at 'called `Result::unwrap()` on an `Err` value: CallingApplicationMistake(ProtocolAlreadyTerminated)', src/keygen/participant.rs:754:61
```

[Here is a link to the failing CI run.](https://github.com/boltlabs-inc/tss-ecdsa/actions/runs/5094736299/jobs/9158907640)

**Comment by marsella** [comment]
Here's another instance:
```

---- keygen::participant::tests::keygen_always_produces_valid_outputs stdout ----
To re-run test with the same randomness, use init_testing_with_seed() with the following seed:
	[64, 210, 52, 76, 132, 125, 165, 168, 184, 243, 94, 15, 210, 216, 73, 81, 155, 78, 227, 79, 255, 17, 139, 83, 17, 211, 104, 235, 158, 32, 191, 159]
To re-run test with the same randomness, use init_testing_with_seed() with the following seed:
	[149, 34, 234, 245, 203, 2, 250, 92, 80, 234, 233, 127, 61, 33, 97, 250, 247, 142, 231, 42, 120, 242, 78, 230, 229, 70, 106, 250, 168, 172, 252, 221]
To re-run test with the same randomness, use init_testing_with_seed() with the following seed:
	[37, 201, 5, 142, 199, 167, 160, 128, 188, 189, 169, 152, 230, 254, 75, 180, 182, 45, 72, 48, 100, 177, 47, 48, 108, 240, 7, 5, 80, 65, 200, 72]
To re-run test with the same randomness, use init_testing_with_seed() with the following seed:
	[243, 246, 226, 202, 24, 173, 167, 32, 236, 212, 177, 197, 80, 55, 145, 144, 95, 20, 45, 210, 74, 228, 168, 140, 45, 80, 253, 125, 90, 189, 93, 144]
thread 'keygen::participant::tests::keygen_always_produces_valid_outputs' panicked at 'called `Result::unwrap()` on an `Err` value: CallingApplicationMistake(ProtocolAlreadyTerminated)', src/keygen/participant.rs:750:61
stack backtrace:
<omitted>
````
[Link to failing CI run](https://github.com/boltlabs-inc/tss-ecdsa/actions/runs/5213141830/attempts/1)

**Comment by tyurek** [comment]
Here's a what happens with the particular seed
`        [76, 62, 227, 201, 204, 136, 37, 38, 226, 80, 103, 165, 196, 83, 7, 168, 70, 187, 36, 42, 242, 186, 124, 76, 165, 76, 120, 49, 49, 113, 54, 230]
`
Participant B finishes the protocol and then receives a Ready message from Participant A. How did this happen? Shouldn't B have waited until receiving a Ready from A before doing the rest of the protocol? Well no, if we received round1 messages from everyone else, then we continue even if we never finished Ready.

In fact, it looks like the comments even predicted this scenario
`// The "right" solution would be to only process the message once the
// "Ready" round is complete, and stashing messages if it is not yet
// complete (a la how we do it in `handle_round_two_msg`).
// Unfortunately, this does not work given the current API because we
// are dealing with a [`BroadcastOutput`] type instead of a [`Message`]
// type.`

**Comment by tyurek** [comment]
I think it would be best to do this for all protocols at once, yeah. Also agree that 1) is a good bug fix for now and other we can decide on later

**Comment by tyurek** [comment]
I wrote some code to test option 1), but found there's still a failure mode: In Keygen there are two triggers for sending round 1 messages: receiving a READY from yourself and trying to send your ROUND2 messages. If the latter pathway occurs, it's possible to terminate before receiving your own READY message, leaving us with the same issue as before.

I see at least two solutions here:
1) Remove Ready entirely and output Round1 messages in response to instantiating the Participant.
2) Stash any message received before you mark yourself as Ready

As for implementation complexity, both approaches might be roughly the same (while 2) might seem simpler, you would have to make sure you aren't hitting bad ordering edge cases). So really I think the question to ask is: Is there any benefit to being able to instantiate a Participant and have it accumulate messages before we're ready to start sending messages ourselves?

**Comment by marsella** [comment]
We discussed offline and decided we want to stick to the protocol description with an explicit/separate Ready message. So, you can't process or generate protocol messages until you've told yourself to start. Stash messages received before then.
